#!/usr/bin/env python3
"""
The QA source of truth, generated — never typed by hand:
  python3 tests/QA/ledger.py      ->  tests/QA/MASTER-QA-LEDGER.md and tests/QA/END-TO-END-CHAINS.md
Inputs (the last real runs only): capabilities.py (every capability, its tests by layer and dimension; xUnit trx,
Playwright last-run.json, Windows windows-*.json under reports/windows), docs/R1-BUGLOG.md (bugs and the commit that
recorded each fix), the Windows evidence (journeys, steps, visual / UX findings).
A capability is PASS only when all three layers are verified by tests that ran and passed; a chain is FULL CHAIN
VERIFIED only when every step passed in ONE continuous run on one Windows machine (the VM: before and after its real
restarts). An agent's word is never evidence: only these files are.
"""
import json, os, re, subprocess, sys, glob
here = os.path.dirname(os.path.abspath(__file__)); repo = os.path.dirname(os.path.dirname(here))
sys.path.insert(0, here)
import capabilities as C

EVIDENCE_URL = 'https://github.com/pcicoffice-bot/onlinebackup-qa/tree/qa-evidence/runs/'

# which capability each bug of docs/R1-BUGLOG.md belongs to (a bug may touch several)
BUGS = {1: ['ST-02', 'AG-04', 'SH-02'], 2: ['BK-05'], 3: ['DB-01', 'DB-02', 'AP-02'], 4: ['SH-01'], 5: ['AP-07'], 6: ['DB-01'],
        7: ['UI-01'], 8: ['UI-01'], 9: ['IN-03'], 10: ['IN-03'], 11: ['ST-02', 'AG-04'], 12: ['ST-04'], 13: ['ST-06'], 14: ['SH-01'],
        15: ['RS-01'], 16: ['RS-02'], 17: ['BK-03'], 18: ['IN-01', 'IN-02'], 19: ['ST-02', 'SH-03'], 20: ['ST-01'], 21: ['BK-03'],
        22: ['AG-01'], 23: ['BK-03', 'ST-04'], 24: ['AG-05'], 25: ['SH-03'], 26: ['SH-02'], 27: ['IN-03'], 28: ['ST-03'], 29: ['ST-04'],
        30: ['RS-01'], 31: ['IN-02', 'UI-05'], 32: ['IN-02', 'UI-05'], 33: ['IN-01', 'IN-04'], 34: ['UI-04']}

def git(*a):
    try: return subprocess.run(['git', '-C', repo] + list(a), capture_output=True, text=True, timeout=60).stdout.strip()
    except Exception: return ''

def bug_commits():
    """the commit that added each bug's row to the bug log (rows are written with their fix)"""
    out = {}
    for n in BUGS:
        h = git('log', '--format=%h', '-S', '| %d | ' % n, '--', 'docs/R1-BUGLOG.md').split('\n')
        out[n] = h[-1] if h and h[-1] else '?'
    return out

def windows_runs():
    """every Windows phase summary under reports/windows: (folder, facts, journeys); a run id per folder"""
    base = os.path.join(here, 'reports', 'windows'); runs = []
    for f in sorted(glob.glob(os.path.join(base, '**', 'windows-*.json'), recursive=True)):
        if not re.match(r'^windows-(main|before-reboot|after-reboot)\.json$', os.path.basename(f)): continue   # not windows-state.json
        try: d = json.load(open(f, encoding='utf-8-sig'))
        except Exception: continue
        runs.append((os.path.dirname(f), d.get('facts', {}), d.get('journeys') or []))
    return runs

def journey_steps(folder, jid):
    try: return json.load(open(os.path.join(folder, jid, 'journey.json'), encoding='utf-8-sig')) or {}
    except Exception: return {}

def rel_evidence(folder):
    r = os.path.relpath(folder, os.path.join(here, 'reports', 'windows')).replace(os.sep, '/')
    return EVIDENCE_URL + r

def ledger(rows, res, commits, wruns):
    global K
    bugs_by_cap = {}
    for n, caps in BUGS.items():
        for c in caps: bugs_by_cap.setdefault(c, []).append(n)
    # visual / UX status per capability from the Windows journeys that prove it
    jv = {}
    for folder, facts, js in wruns:
        for j in js: jv.setdefault(j['id'], []).append((j.get('visual'), j.get('ux'), folder))
    L = ['# MASTER QA LEDGER — generated by `tests/QA/ledger.py` from the last real runs (do not edit by hand)', '',
         'Status: **PASS** = verified in all three layers (component, integration, end-to-end) by tests that ran and passed; '
         '**PARTIAL** = some layer missing (listed); **NOT TESTED** = no layer verified; **FAIL** = a test of it fails now. '
         'Windows tests count only when the journey really ran on Windows and passed. Evidence = the test ids below, whose '
         'results come from `tests/QA/reports/trx/xunit.trx`, `tests/QA/reports/last-run.json` and the Windows runs in the branch `qa-evidence`.', '']
    crit = [r for r in rows if r['critical']]
    def n(st): return sum(1 for r in crit if r['status'] == st)
    L.append('Critical capabilities: %d — PASS %d, PARTIAL %d, NOT TESTED %d, FAIL %d.' % (len(crit), n('FULL'), n('PARTIAL'), n('NONE'), n('FAILING')))
    L.append('')
    L.append('| ID | Capability | Crit. | Status | Component | Integration | E2E | Windows | Failure | Recovery | Visual/UX | Bugs (fix commit) | Missing |')
    L.append('|---|---|---|---|---|---|---|---|---|---|---|---|---|')
    st = {'FULL': 'PASS', 'PARTIAL': 'PARTIAL', 'NONE': 'NOT TESTED', 'FAILING': 'FAIL'}
    for r in rows:
        lay = r['layers']
        def lv(Ly): return '%s (%d)' % (lay[Ly]['status'], len(lay[Ly].get('tests', [])) if isinstance(lay[Ly].get('tests'), list) else 0)
        dims = r['dims']
        win = sorted(set(t for d in dims.values() if not isinstance(d, C.NA) for t in d if t.startswith('win:')))
        winst = ', '.join('%s %s' % (t[4:], {'Passed': 'PASS', 'Failed': 'FAIL'}.get(res.get(t), 'NOT RUN')) for t in win) or '—'
        def dim(k):
            d = dims.get(k)
            if isinstance(d, C.NA): return 'N/A'
            ok = [t for t in d if res.get(t) == 'Passed' or C.resolve(t, res) == 'Passed']
            return '%d/%d' % (len(ok), len(d)) if d else '0'
        vu = []
        for t in win:
            for v, u, f in jv.get(t[4:], []): vu.append('%s: V %s, UX %s' % (t[4:], v, u))
        bl = ', '.join('%d (%s)' % (b, commits.get(b, '?')) for b in sorted(bugs_by_cap.get(r['id'], []))) or '—'
        miss = '; '.join('%s: %s' % (Ly, ', '.join(lay[Ly]['missing'])) for Ly in C.LAYERS if lay[Ly]['status'] != 'VERIFIED') or '—'
        L.append('| %s | %s | %s | **%s** | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
            r['id'], r['name'], 'yes' if r['critical'] else 'no', st[r['status']], lay['component']['status'], lay['integration']['status'], lay['e2e']['status'],
            winst, dim('failure'), dim('recovery'), '; '.join(sorted(set(vu))) or '—', bl, miss))
    L += ['', '## Production files and tests per capability', '']
    for r in rows:
        L.append('### %s %s' % (r['id'], r['name']))
        L.append('- Production: `%s`' % r['code'])
        for Ly in C.LAYERS:
            ts = sorted(set(t for d in r['dims'].values() if not isinstance(d, C.NA) for t in d if C.layer_of(t, K) == Ly))
            L.append('- %s: %s' % (Ly, ', '.join('%s %s' % (t, {'Passed': 'PASS', 'Failed': 'FAIL', 'Skipped': 'NOT TESTED'}.get(C.resolve(t, res) if t.startswith('qa:') else res.get(t), 'NOT RUN')) for t in ts) or 'none'))
        L.append('- Regression: %s' % (', '.join(str(x) for x in (r.get('regression') or [])) or '—'))
        L.append('')
    open(os.path.join(here, 'MASTER-QA-LEDGER.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')

# The chains: every step names the journey and the step (by its title) whose result proves it.
CHAINS = [
    ('C1', 'Client lifecycle on a fresh Windows (the full chain)', [
        ('Download the client Setup.exe from the server', 'W01', 'Download the client Setup.exe*'),
        ('Setup launch (the installer window opens)', 'W03', 'Setup.exe opens its window'),
        ('License: Install disabled until accepted', 'W03', 'Install is disabled before*'),
        ('License accepted', 'W03', 'Accept the license*'),
        ('Install (progress, then Finish "is installed")', 'W03', 'Installer 05 - Finish'),
        ('Service created, automatic, Running (Windows service manager)', 'W03', 'Windows service manager:*'),
        ('Its process runs from the installed program', 'W03', 'Its process runs*'),
        ('Listed in installed programs; files on disk', 'W03', 'Installed programs list*'),
        ('Client opens (Finish with "Open now")', 'W03', 'Finish with "Open now"*'),
        ('Sign in through the window', 'W04', 'Client 04 - Connected*'),
        ('Server sees the client (registered, connected)', 'W04', 'ORACLE (server): this computer is registered*'),
        ('Configure the backup in the window (set on the server with the folder)', 'W05', 'ORACLE (server): the backup set exists*'),
        ('Backup: job completes, server history records it with its bytes', 'W05', 'Backup 1 - result'),
        ('Delete the source', 'W05', 'Restore 1 - the source folder is deleted'),
        ('Restore in the window; SHA-256 of every file identical', 'W05', 'Restore 1 - ORACLE*'),
        ('Restart Windows (real)', 'W19', 'Windows really restarted'),
        ('Services back by themselves', 'W19', 'Both services came back*'),
        ('Agent reconnects (server view)', 'W19', 'The agent is connected again*'),
        ('No ghost run, no locked set', 'W19', 'No ghost run, no locked set'),
        ('Schedule kept', 'W19', 'The schedule is kept'),
        ('Second backup', 'W19', 'Backup after the restart - result'),
        ('Second restore; SHA-256 identical', 'W19', 'Restore after the restart - ORACLE*'),
        ('Uninstall (service, entry and files gone; backups stay on the server)', 'W21', 'Removed: no service*'),
    ]),
    ('C2', 'Crash and recovery on Windows (agent killed mid-backup)', [
        ('Backup running (server live view)', 'W07', 'The backup is running*'),
        ('Service process killed', 'W07', 'Kill the service process*'),
        ('Windows restarts the service by itself', 'W07', 'Windows restarts the service by itself*'),
        ('No ghost run; the killed run recorded', 'W07', 'No ghost*'),
        ('Next backup', 'W07', 'Backup after the crash - result'),
        ('Restore; SHA-256 identical', 'W07', 'Restore after the crash - ORACLE*'),
    ]),
    ('C3', 'Server installation from the package', [
        ('install-server.ps1 (Windows PowerShell) → service Running', 'W01', 'install-server.ps1*'),
        ('Automatic start, restart on failure', 'W01', 'Server service: automatic start*'),
        ('Admin sign-in over HTTPS with the authenticator', 'W01', 'Admin sign-in*'),
        ('Customer created; client package downloaded', 'W01', 'Download the client Setup.exe*'),
    ]),
]

def step_result(folder, jid, pattern):
    import fnmatch
    j = journey_steps(folder, jid)
    hits = [s for s in (j.get('steps') or []) if fnmatch.fnmatchcase(s.get('step', ''), pattern) and s.get('result') in ('PASS', 'FAIL')]
    if not hits: return None
    return 'FAIL' if any(s['result'] == 'FAIL' for s in hits) else 'PASS', hits[-1]

def chains(wruns):
    L = ['# END-TO-END CHAINS — generated by `tests/QA/ledger.py` (do not edit by hand)', '',
         'Each step names the journey and step whose real result proves it. **FULL CHAIN VERIFIED** only when every step '
         'passed in ONE continuous run on ONE Windows machine (the VM: the same disk before and after its real restarts). '
         'Ten separate passes on different machines or runs are listed, but they never make a chain verified.', '']
    # group the phases by run: a VM run = runs/<id>/vm/out/vm-*; the hosted Windows job = runs/<id>
    groups = {}
    for folder, facts, js in wruns:
        rel = os.path.relpath(folder, os.path.join(here, 'reports', 'windows')).replace(os.sep, '/')
        parts = rel.split('/')
        key = (parts[0], 'vm' if 'vm' in parts else 'hosted')
        groups.setdefault(key, []).append((folder, facts, {j['id']: j for j in js}))
    for cid, title, steps in CHAINS:
        L.append('## %s %s' % (cid, title)); L.append('')
        if not groups: L.append('No Windows run in reports/windows: every step NOT TESTED.'); L.append('')
        for (run, kind), phases in sorted(groups.items()):
            machine = '; '.join(sorted(set(str(f.get('windows', '?')) for _, f, _ in phases)))
            L.append('### run %s — %s (%s)' % (run, 'virtual machine, real restarts' if kind == 'vm' else 'hosted Windows runner, no restart possible', machine))
            L.append(''); L.append('| # | Step | Journey | Result | Evidence |'); L.append('|---|---|---|---|---|')
            allpass = True
            # ONE machine: every phase of the run on the same computer (a VM that was replaced or reinstalled half-way
            # is not one continuous run)
            computers = set(str(f.get('computer', '?')) for _, f, _ in phases)
            if len(computers) != 1 or '?' in computers or 'None' in computers:
                allpass = False
            for i, (name, jid, pat) in enumerate(steps, 1):
                found = []
                for folder, facts, js in phases:
                    if jid in js:
                        r = step_result(folder, jid, pat)
                        if r: found.append((r, folder))
                if not found:
                    allpass = False; L.append('| %d | %s | %s | NOT TESTED | — |' % (i, name, jid)); continue
                # a step that ran in several phases (W19 after each restart) passes only if it passed in EVERY one: the
                # last phase alone (a later PASS) once hid an earlier FAIL
                bad = [f for f in found if f[0][0] != 'PASS']
                (res, s), folder = bad[0] if bad else found[-1]
                if res != 'PASS': allpass = False
                ev = rel_evidence(os.path.join(folder, jid)) + ((' · ' + s['screenshot']) if str(s.get('screenshot', '')).endswith('.png') else '')
                L.append('| %d | %s | %s | %s | %s — %s |' % (i, name, jid, res, ev, str(s.get('actual', ''))[:160].replace('|', '/').replace('\n', ' ')))
            verdict = 'FULL CHAIN VERIFIED' if (allpass and (kind == 'vm' or cid != 'C1')) else 'NOT VERIFIED'
            if cid == 'C1' and kind != 'vm' and allpass: verdict = 'NOT VERIFIED (no real restart on a hosted runner)'
            L.append('')
            if len(computers) != 1: L.append('The phases of this run name %d computers (%s): not one continuous run on one machine.' % (len(computers), ', '.join(sorted(computers)))); L.append('')
            L.append('**%s %s, run %s: %s**' % (cid, title, run, verdict)); L.append('')
    open(os.path.join(here, 'END-TO-END-CHAINS.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')

if __name__ == '__main__':
    res = C.results(); rows = C.evaluate(res); wr = windows_runs(); K = C.xunit_kinds()
    ledger(rows, res, bug_commits(), wr); chains(wr)
    print('MASTER-QA-LEDGER.md and END-TO-END-CHAINS.md written;', len(wr), 'Windows phase(s) read')
