"""
The component contract of every capability, written BEFORE its tests are judged: what it is for, a known input, and the
output expected from that input. capabilities.py refuses to call a component layer verified without one.
id: (purpose, known input, expected output)
"""
SPEC = {
 'BK-01': ('Copy a folder tree to the server so that any run can be restored exactly',
           'a tree of new, changed, deleted and permission-changed files; two runs',
           'run 2 sends only what changed; every point restores byte-identical (SHA-256); deleted files gone from the newest point only'),
 'BK-02': ('Send only the changed parts of large files, and keep every point restorable',
           'a large file changed in the middle N times; incremental and differential modes',
           'each delta is small; every point of the chain restores identical; past the chain limit a new full copy is sent'),
 'BK-03': ('Back up with restic to the server\'s restic store',
           'a source tree, two runs with one change',
           'second run adds only the change; restore identical; `restic check` clean; another set cannot read the repository'),
 'BK-04': ('Leave out what the set excludes; follow links only when asked',
           'a tree with excluded folders, filter patterns and a symbolic link',
           'excluded items absent from the restore, included ones identical; the link followed only with the option on'),
 'BK-05': ('A file or folder that cannot be read is an error, never a silent success',
           'a source with an unreadable subfolder; a source that is gone; all sources gone',
           'partly unreadable = success with error (red); all gone = failure; last good backup kept and still restorable'),
 'BK-06': ('Copy files that are open or locked by another program, consistent to one moment',
           'a file held open with an exclusive lock and written during the backup',
           'the file is in the backup with its content at snapshot time; the shadow copy is removed afterwards, also on failure'),
 'BK-07': ('Stop a backup at its maximum duration or on request, and go on next time',
           'a slow backup with a 1-minute limit; a stop sent from the admin site',
           'the run ends as stopped (not success), nothing half-stored is visible, the next run completes'),
 'BK-08': ('Honour the upload limit, compression and priority settings',
           'a 20 MB source with a 1 MB/s limit; compression on / off',
           'the transfer takes about 20 s; with compression the stored size is smaller; restore identical either way'),
 'BK-09': ('Run the set\'s commands before and after the backup, within a time limit',
           'a pre-command that succeeds, one that fails, one that never ends',
           'output logged; a failure stops the backup only when the set says so; a stuck command ends at the limit'),
 'BK-10': ('Keep a second copy on a local disk / NAS beside the online one',
           'a set with a local copy path',
           'the local copy restores without the server, identical; a full local disk is a warning, not a lost online backup'),
 'DB-01': ('Back up SQL Server databases with native full / differential / log backups',
           'a database with transactions committed between runs',
           'restored .bak files load and contain every committed transaction; not enough room → the database skipped with a clear error'),
 'DB-02': ('Dump MySQL / PostgreSQL databases',
           'two databases with known rows; one database that fails',
           'the dumps load into a new server with the same rows; the failing database is an error; passwords never in a log'),
 'DB-03': ('Run an Oracle RMAN online backup', 'an RMAN script and password', 'RMAN gets the password only on stdin; a failed RMAN run keeps the previous backup'),
 'DB-04': ('Back up HCL Domino data folders', 'notes.ini with a data folder', 'the folders from notes.ini are backed up after the cache is flushed'),
 'AP-01': ('Back up the Windows System State', 'a Windows server', 'wbadmin output in the backup; a failure of wbadmin is a failed run'),
 'AP-02': ('Back up a bare-metal image of the computer', 'a Windows computer with a system volume', 'an image that boots on new hardware; tool failure = failed run'),
 'AP-03': ('Back up Hyper-V virtual machines', 'a VM, running', 'export of the VM restores and starts; a failed export is a failed run'),
 'AP-04': ('Back up VMware virtual machines', 'a VM on ESXi / vCenter', 'the VM restores to another datastore under a new name'),
 'AP-05': ('Back up Microsoft 365 mail, OneDrive and Teams', 'a tenant with mail, files and chats', 'items restored to the mailbox / OneDrive with their content'),
 'AP-06': ('Back up Google Workspace', 'a domain with Gmail and Drive', 'items restored with their content'),
 'AP-07': ('Run any external program safely', 'a program that hangs; one that writes much to both streams; one that spawns children',
           'stopped at its limit with its children; both streams read in full; never a hung backup or installation'),
 'RS-01': ('Restore everything, a folder or one file, from any point', 'a set with 3 points; a request for point 2, one file',
           'exactly the requested files, byte-identical to that point (SHA-256)'),
 'RS-02': ('Restore to the original place safely', 'files that exist at the target, overwrite off / on',
           'off: existing files kept and the result says how many were skipped; on: replaced; a failed file = error'),
 'RS-03': ('Restore restic sets', 'a restic set with 2 snapshots', 'identical files from the chosen snapshot'),
 'RS-04': ('Restore from the website as a ZIP download', 'the encryption password, a point, 2 files',
           'the ZIP holds exactly those files, identical; a wrong password refused; a hung restic stopped with a clear error'),
 'RS-05': ('Restore on a new computer after the old one is lost', 'a new computer, the account and the encryption password',
           'the keys come back, the local index is rebuilt, every file restores identical'),
 'RS-06': ('Prove automatically that the backup can be restored', 'a set with the restore test on', 'sample restored and compared; no source to compare = NOT CHECKED, never FAILED'),
 'ST-01': ('Store a run all-or-nothing on the server', 'a run committed; the server killed during the commit; a truncated object',
           'after restart the run is either fully there or not at all; truncated objects refused; repeated commit answered the same'),
 'ST-02': ('Never leave a run open or "Running" after the computer died', 'a run with no sign of life for 5 minutes; the same run reported by 3 paths',
           'closed and recorded once as interrupted; the set can back up again at once'),
 'ST-03': ('Delete old versions by the retention policy, never the current one', 'versions over 40 days; policy 30 days / N jobs / GFS',
           'only versions outside the policy deleted; every kept point restores identical; the current version never deleted'),
 'ST-04': ('Find damaged stored data, quarantine it, get it again', 'a stored object with flipped bytes', 'found, quarantined, resent from the source; the index can be rebuilt from the objects'),
 'ST-05': ('Stop new backups at the quota and keep what exists', 'a user at 100 % of the quota', 'new backup refused with QUOTA; existing points restore; the warning at the set percentage'),
 'ST-06': ('Say clearly that the server disk is full', 'a server disk filled during a backup', '507 DISK_FULL, a clear message on the computer, one alert to the administrators, space of the failed run given back'),
 'ST-07': ('Copy everything to a second server', 'a commit on the main server', 'the same objects, database and logs on the replica'),
 'ST-08': ('Open data written by earlier versions', 'a store written by version N-1', 'every point restores identical after the upgrade'),
 'ST-09': ('Undo deleting a set or a customer', 'a deleted set', 'restorable from the recycle bin until it expires'),
 'ST-10': ('Back up the server settings', 'the server configuration', 'a copy that restores the settings'),
 'AG-01': ('Start backups on time: once per due time, never twice, and catch up missed ones', 'a schedule of 3 times a day; the computer off at one of them; a restart of the service',
           'each due time runs once; a missed time runs once at start-up; nothing runs twice after a restart'),
 'AG-02': ('"Back up now" and "Stop" from the admin site reach the computer', 'a press of Back up now; a press of Stop', 'the run starts within a minute; Stop ends it as stopped'),
 'AG-03': ('Settings changed on the server reach the computer', 'a set edited in the admin site', 'the computer uses the new settings in its next run'),
 'AG-04': ('Keep the server informed while a run is alive', 'a long run; the agent killed', 'progress every minute; the dead run reported at the next start'),
 'AG-05': ('Survive network trouble', 'the line cut during upload; the server unreachable; a request whose answer is lost',
           'the run resumes or ends as failed with a clear reason; a repeated request is not counted twice; the next run completes and restores identical'),
 'AG-06': ('Recover from lost or damaged local state', 'the local index deleted / damaged', 'rebuilt from the server; the next backup is correct and restores identical'),
 'AG-07': ('Talk TLS 1.2 on old Windows and pin the server certificate', 'a server certificate; a different certificate', 'the pinned one accepted; another refused'),
 'AG-08': ('Run on .NET 4.0 (old Windows)', 'the net40 build under mono', 'the same backup and restore results as net8'),
 'AU-01': ('Only administrators get in, with two steps', 'right / wrong password, right / wrong code, 10 failures, sign-out',
           'right + right = in; anything wrong refused; locked after failures; after sign-out the session no longer works'),
 'AU-02': ('Customers and their computers sign in', 'a login, a registered device token, a revoked token', 'valid = allowed; revoked = refused at once'),
 'AU-03': ('Sign up from the client with the contract', 'a new customer accepting the contract', 'account created with the contract recorded'),
 'AU-04': ('Block addresses that guess or scan', 'many failed sign-ins from one address', 'the address blocked; others not affected; the administrator alerted'),
 'AU-05': ('Encrypt data so that only the key holder can read it', 'data with key A; reading with key B; a changed byte', 'B cannot read; the changed byte detected'),
 'AU-06': ('Each reseller sees only its own customers', 'two vendors with customers', 'each sees and changes only its own'),
 'AU-07': ('The API refuses junk and attacks clearly', 'malformed, oversized, path-traversal and unauthenticated requests', 'clear 4xx refusals; nothing written outside its place'),
 'IN-01': ('Install the server', 'a clean Windows Server', 'service running, certificate bound, port open, admin site answers'),
 'IN-02': ('Install / uninstall / reinstall the client', 'Setup.exe on a clean computer, then uninstall, then reinstall', 'service running, registration kept on reinstall, nothing left after uninstall'),
 'IN-03': ('Update the client all-or-nothing', 'an update while the service runs; a file that cannot be replaced', 'all files new and the service back; or all old (rolled back) and the result says why'),
 'IN-04': ('Update the server only with a signed package', 'a signed package; a changed package', 'signed installed with data kept; changed refused'),
 'IN-05': ('Build client packages with branding and the server inside', 'a branded package request', 'Windows / Linux / Mac packages that connect to this server'),
 'IN-06': ('Survive a reboot', 'a reboot during idle and during a backup', 'service back; the interrupted run recorded; the next run completes'),
 'SH-01': ('Show the truth: last backup vs last result, every run in the history', 'a success then a failure', 'last backup = the success; last result = the failure (red); both runs in the history'),
 'SH-02': ('Show only runs that are really running', 'a run that ended; a run whose computer died', 'neither stays in "Running now"'),
 'SH-03': ('Send the right mail, and no false one', 'a success, a failure, a missed backup, quota, disk full', 'one mail of the right kind each; no failure mail for a success; no duplicate'),
 'SH-04': ('Open and close service calls from backup results', 'a failure, then a success', 'a call opened, then closed'),
 'SH-05': ('Suspect ransomware and freeze retention', 'a run that changes most files with one new extension', 'retention frozen, administrators alerted'),
 'SH-06': ('Manage computers', 'disconnect a computer; move it to another customer', 'its token stops working; backups move with it'),
 'SH-07': ('Enforce the licence', 'an edition with limits; a check-in', 'limits applied; check-in recorded'),
 'UI-01': ('Every admin page opens without errors', 'each page, reload, sign-out', 'no console errors; sign-out ends the session'),
 'UI-02': ('The set editor saves every tab', 'a change on each tab', 'read back the same; reaches the computer'),
 'UI-03': ('The admin site shows the truth after failures', 'a failed run; a dead run', 'red, failed, not running'),
 'UI-04': ('The client window works', 'each page; typing in a field during a refresh', 'pages open; typed text kept'),
 'UI-05': ('The client installation wizard', 'Welcome → License → Install → Finish', 'each step reachable; Back / Cancel work; the service installed'),
 'UI-06': ('Partner portal and licensing centre', 'a partner session', 'licences and packages managed'),
 'UI-07': ('Every screen in 13 languages, Hebrew right-to-left', 'each language', 'no missing keys; Hebrew screens laid out right-to-left'),
 'UI-08': ('AI explains failures and forecasts', 'a failed run log', 'an explanation without secrets'),
 'CO-01': ('Read and write the shared formats exactly, and never leave a half-written state file', 'messages, a profile with unknown attributes, log lines, a write interrupted midway',
           'what is written reads back the same; unknown attributes are kept; a reader never sees a half file'),
 'UI-09': ('Large installations stay fast', '500 customers, 5 000 sets', 'pages within the time limit'),
}
